### ISSUE TITLE
Sign for Uris Library (Cocktail Lounge) group study rooms

### ISSUE THREAD

**Issue by JonLadley** [cul-it/signage#123] opened 2019-04-08 20:25 UTC
The renovation project purchased an iPad and stand to display LibCal data for group study rooms 4B02, 4B03, 4B04 in Uris Library.

Pete Magnus has the iPad. I'm honestly not sure what to do next.

**Comment by cappadona** [comment] 2019-04-08 20:39
Hi @JonLadley. Thanks for the heads up. Some questions to get us started...

1. Are you looking to reproduce something like the [Mann studyrooms display](http://signage.library.cornell.edu/mann/spaces/studyrooms)?
1. Are you working with anyone else?

   > any additional stakeholders who should be included in this process
1. What's your time frame?

Thanks.

**Comment by JonLadley** [comment] 2019-04-10 16:19
Thanks Nick. Your example from Mann looks perfect. Bonna Boettcher, Wendy Wilcox, and Pete Magnus are the other immediate stakeholders. If there's any way it could be ready by 5/10, that would be great.

**Comment by cappadona** [comment] 2019-04-19 14:55
You're welcome @JonLadley.

Is it safe to assume that we have a green light from the rest of the stakeholders?

I wanted to point out that the Mann Studyrooms sign is rendered on a 40" LCD (including photo below of an early beta version).

![DSC00063](https://user-images.githubusercontent.com/409842/56429482-05499880-6291-11e9-80e6-e5f7e3b84434.JPG)

I'm not sure exactly which iPad model was purchased, but it's fair to say that no matter the model, the Uris Cocktail lounge sign will be significantly smaller. I'm also not familiar with the layout of the study rooms in the space, but I'm assuming that they are all in close proximity to each other and that a central location for the iPad stand has been selected?

**Comment by Mewnice** [comment] 2019-04-23 16:48
I've followed Nick's instructions and the iPad is pretty much set up.  Two issues:
1) What Web site to use?  Right now it's configured for Mann, since no one's given me info for the Uris one.  (I'll send this question via email so as to get all the players.)
2) I have touchscreen turned on in both Kiosk Pro Lite and Guided Access, yet the screen is not responding to my touch.  Bonna said something about getting it to work once she figured out where to touch the screen - so I'll send this comment via email as well.

**Comment by cappadona** [comment] 2019-04-23 18:03
Hi @Mewnice. That's great news about the iPad.

1. The Uris sign doesn't exist at the moment, so there's no URL just yet 😄 
2. The only link on the [Mann studyrooms sign](http://signage.library.cornell.edu/mann/spaces/studyrooms) is the URL `mannlib.cornell.edu/reserve` at the top of the screen

**Comment by Mewnice** [comment] 2019-04-23 19:02
I clicked on mannlib.cornell.edu/reserve and got "this site is not allowed".  I then went into Kiosk and was able to look at block logs.  I'm not sure why the site was being blocked, since I had added *.mannlib.cornell.edu. https vs http, maybe?  Anyway, I added specific sites listed in the logs.  Now when I click on the Reserve link, I wait a few seconds, then suddenly I'm taken to a page with Reservable Rooms.  This page has the Mann Library footer with lots of other links.  I can get to the Haiku page (by virtue of it being mannlib; I can't get to NYCCSC - not allowed, and I'm assuming it's pointing somewhere outside mannlib and library.  
I'll wait until Uris' sign is set up - then I can test with that URL to try to understand allowed/blocked better.
The sign goes back to the reserve homepage after 120 seconds - success there.

**Comment by cappadona** [comment] 2019-04-23 19:29
Thanks @Mewnice.

Yeah...[NYCCSC](http://nyclimatescience.org) is not a cornell.edu domain. Probably makes sense to sit tight until we have the Uris sign ready for testing but I suspect we'll be pointing that reserve button link to `spaces.library.cornell.edu`.

**Comment by Mewnice** [comment] 2019-05-02 13:06
Is the Uris sign ready for testing yet?  Isn't there a May 10 deadline for this?  Is there anything I should be doing right now?  Thanks.

**Comment by cappadona** [comment] 2019-05-02 13:15
Morning @Mewnice. It's not ready...actually I haven't started on it just yet.

Still isn't clear to me if we had the green light to proceed. My last message in our email thread from `4/23` asking exactly this went without a response. Have you heard otherwise?

**Comment by cappadona** [comment] 2019-05-03 12:51
Hi again @Mewnice. Looks like we have the green light 😄 so I'll start working on this and should have a test instance of the app for everyone to review early next week.

**Comment by cappadona** [comment] 2019-05-06 14:15
Morning @Mewnice @JonLadley. [Initial sign](https://signage-stg-pr-129.herokuapp.com/uris/spaces/cocktail) is available for everyone to review.

A few important points to keep in mind:
1. This is only a temporary URL.

   > The proposed permanent URL is: https://signage.library.cornell.edu/uris/spaces/cocktail
1. I'm using the main Uris hours for now since no hours have been configured in
LibCal for the **Uris Cocktail Lounge Group Studies** _dept_
1. The reserve link at the top (`spaces.library.cornell.edu/reserve/uris/cocktail`) resolves to a 404 at the moment, but I can configure the friendly URL for the category space in LibCal if everyone is good with this suggestion

**Comment by Mewnice** [comment] 2019-05-07 19:03
@cappadona @JonLadley I'm waiting for feedback, right, before I do the final configuration of the iPad?

**Comment by JonLadley** [comment] 2019-05-07 19:15
Hey @cappadona @Mewnice Bethany Silfer from Olin/Uris Access Services should be reaching out to get on this issue in order to represent that group

**Comment by Mewnice** [comment] 2019-05-10 12:43
@cappadona @JonLadley  I haven't heard anything from Bethany.  And I'm waiting for permanent URL, but I think Nick is waiting for go-ahead?

**Comment by cappadona** [comment] 2019-05-10 12:46
Morning @Mewnice, I also haven't heard from Bethany.

You could run with the [proposed permanent URL from above](https://github.com/cul-it/signage/issues/123#issuecomment-489636711), but it will return an error for now until we have the sign finalized and I deploy to production.

**Comment by Mewnice** [comment] 2019-05-10 17:34
@cappadona @JonLadley  Just ran into Bethany (right after running into Jon in the hallway!).  Bethany reports that she signed up for GitHub.  And she's thinking Liz Kluz should be the contact on this instead.  Meanwhile, the sign won't be needed until Senior Week, she says.

**Comment by cappadona** [comment] 2019-05-10 17:56
Thanks for the update @Mewnice. If Bethany sends me her GitHub username I can add her to the organization.

**Comment by Mewnice** [comment] 2019-05-21 17:37
@cappadona @JonLadley @BSilfer  Whose court has the ball on this project?  Or did it roll under the couch (note my avatar)? Thx!

**Comment by BSilfer** [comment] 2019-05-21 17:51
There will be a separate Uris hours entry for the cocktail lounge and those will be the hours to link to. Basically the room and those spaces will be available almost 27/7/365. Only exceptions will be closed the night before a University Holiday and closed on University Holidays. Other than that, they will be available for reservations.

**Comment by cappadona** [comment] 2019-05-21 20:17
Thanks @BSilfer. I still don't see any hours for the cocktail lounge in LibCal [as mentioned above](https://github.com/cul-it/signage/issues/123#issuecomment-489636711). Do you have access to the LibCal admin or is someone else responsible for managing the hours?

**Comment by BSilfer** [comment] 2019-05-21 20:44
Hi,

We don't have hours in yet because the room is behind schedule a bit. No official date for opening yet.

Bethany



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by JonLadley** [comment] 2019-05-22 18:43
Our go live date for the sign has been pushed to 5/31. Does that sound doable?

**Comment by Mewnice** [comment] 2019-05-22 18:50
As long as Nick has the info he needs to make this work...  He's given me a probable URL to use, but last I checked, it wasn't live.

**Comment by cappadona** [comment] 2019-05-22 19:29
Thanks @JonLadley (and @Mewnice).

`5/31` should be doable as long as I can get an answer on my [questions from above](https://github.com/cul-it/signage/issues/123#issuecomment-489636711).

To reiterate:

1. LibCal hours for the Cocktail Lounge are currently undefined. Have we identified who will be managing the hours in LibCal and can someone put me in touch with this person?
   > I need to verify that I'm referencing the correct `deptID` within LibCal

1. Are the stakeholders okay with the proposed reserve URL displayed at the top of the page? `spaces.library.cornell.edu/reserve/uris/cocktail`
   > It currently resolves to a `404`, but I can configure the friendly URL for the category space in LibCal if we have consensus


If you give me a couple minutes I'll spin up the review app again (it is automatically destroyed after 5 days of inactivity).

**Comment by cappadona** [comment] 2019-05-22 19:33
@JonLadley @Mewnice @BSilfer 

[Draft of Uris Cocktail Lounge sign is alive once again](https://signage-stg-pr-129.herokuapp.com/uris/spaces/cocktail).

**Comment by Mewnice** [comment] 2019-05-29 12:29
@cappadona Have you gotten responses to your questions asked 7 days ago?  I don't like being this close to deadline and not being able to test/document...

**Comment by cappadona** [comment] 2019-05-29 12:57
Morning @Mewnice. I'm with you...I haven't heard anything since Bethany's email to Patrick on `5/22` requesting that hours be setup for the Cocktail Lounge. I just checked LibCal and there is no change – no hours are defined for the Cocktail Lounge 😞 

@BSilfer @JonLadley Is it game on for `5/31` or has the date slipped?

**Comment by JonLadley** [comment] 2019-05-29 14:56
@cappadona Yes, the public opening date is a bit of a moving target right now. I'm waiting to hear back from the project manager, and will figure out a new date after I have some answers. I'll keep everyone posted.

**Comment by BSilfer** [comment] 2019-06-07 14:10
The newest date is 6/10/19. The Hours are on the Uris Library Hours site 24hr space.

**Comment by dbranchini** [comment] 2019-06-07 14:39
@BSilfer and @JonLadley, thanks for the notice on when the space will be opening. Nick and Amy, (software and hardware respectively) still have questions that have not been answered yet. With this late notices, the soonest they'll be able to get the sign up and running is mid-week next week.

**Comment by Mewnice** [comment] 2019-06-07 15:01
@BSilfer @JonLadley Once this is done, who do I hand the iPad over to?  And who will be the first line of contact for minor issues?  (We'll help, of course, but Desktop Services doesn't want to "own" the device.) And who has a key to the case this is going into?

**Comment by BSilfer** [comment] 2019-06-07 15:05
All good questions. I don't know the answers to these, but I'll try to find out.

**Comment by cappadona** [comment] 2019-06-07 15:45
I have updated the app to account for the LibCal hours and use a reserve URL of `https://spaces.library.cornell.edu/reserve/uris-cocktail`.

I've also gone ahead and configured the spaces and associated space category in LibCal:
* linked the category to the appropriate LibCal hours
* set all 3 spaces to **Active**
* the category is now **Private** so the rooms are hidden from the public by default and are only accessible if you know the reserve URL

---

**Important Note:** Usually we test the full workflow for a couple days before going live with a sign. We add some test reservations in LibCal and ensure they're displaying properly on the sign and that the opening/closing is reflected properly, etc. None of this has happened with the Uris Cocktail sign so we should all be prepared for potential surprises next week.

**Comment by JonLadley** [comment] 2019-06-07 16:09
Thanks @cappadona and @Mewnice. There is no expectation that the iPad will be ready by Monday, so if you need some extra days to test and configure, that's fine. I assume Olin/Uris Access Services will own the device and hold the key, but I'll let @BSilfer confirm that. I believe CJ currently has the key.

**Comment by Mewnice** [comment] 2019-06-11 13:08
@JonLadley @cappadona @BSilfer Nick and I are ready to hand over the iPad.   I'd like to go with someone - Bethany? - to make sure it fits properly in the case and to walk you through how it works.  (You don't need all the details, just the basics.)  I was going to suggest Liz but I see she's out OOO until June 27...

**Comment by BSilfer** [comment] 2019-06-11 13:45
Hi, Yes you can give it to me and show me the basics. I'll figure out who has the case, key, etc. Here are some times I have several times available this Thursday to meet between 10-4. Let me know when and where. Thanks

**Comment by Mewnice** [comment] 2019-06-11 15:52
I just stuck something in Bethany’s calendar for Thursday.

Amy

**Comment by cappadona** [comment] 2019-06-27 20:13
We've been live for two weeks now and I haven't heard about any issues so closing this for now. Thanks everyone!

**Closed by cappadona** 2019-06-27 20:13 UTC
